"""Create user table

Revision ID: 0cf8f947e7b8
Revises: 819863729709
Create Date: 2024-10-28 09:09:10.990542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf8f947e7b8'
down_revision = '819863729709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_title', sa.String(length=100), nullable=True),
    sa.Column('event_location', sa.String(length=100), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('event_duration', sa.Time(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('event_joiners',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_joiners')
    op.drop_table('event')
    op.drop_table('user')
    # ### end Alembic commands ###
