"""Username Unique

Revision ID: 819863729709
Revises: c71e05217206
Create Date: 2024-10-26 11:31:33.234498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819863729709'
down_revision = 'c71e05217206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
